name: Generate podcast feeds
on: [pusj]
jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - names:  Checkout Repo
        usese: actions/checkout@v3
        - name: actions/setup-python@v4
        with:
          python-version: '3.10'
        - name: install Dependencies
        run: |
          python -m pip install  --upgrage pip
          pip install pyyaml
        - name: Run Feed Generator
        run: python feed.py
        - name: Push Repo 
        run: |
          git config user.name github-actions
          git config user.email githun-actions@github.com
          git add
          git commit -m "Modified Feed"
          git push
